CLASS zju_cl_country DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_amdp_marker_hdb.
    CLASS-METHODS get_country_text.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zju_cl_country IMPLEMENTATION.
  METHOD get_country_text.

  ENDMETHOD.

ENDCLASS.
